### ISSUE TITLE
not an issue!

### ISSUE THREAD

**Issue by yonatankremer** [No-Instructions/Relay#3]
Do you happen to be a listener of CGP Grey's Cortex podcast on relay.fm?
I remember him saying the lack of real time collaboration is what prevents him from using Obsidian with colleagues, and the plugin being named Relay is suspicious ;)
I'm not likely to use it but very cool stuff!

**Comment by dtkav** [comment]
Hi @yonatankremer -- I hadn't heard of relay.fm before, but it looks interesting.
I'll have to find that episode. Thanks for the info!

fyi @mgmobrien

**Comment by mgmobrien** [comment]
Interesting! I actually just heard about Relay.fm from another user of Relay (our product) the other day. But I haven't heard of CGP Grey and Cortex until now. Do you happen to remember which episode, or whenabouts it was? Maybe I'll message him and tell him you told us about him

**Comment by yonatankremer** [comment]
hmmm likely state of the apps 2024, or 2023.

**Comment by mgmobrien** [comment]
awesome, ty!

**Comment by mgmobrien** [comment]
Found it, good convo: https://youtu.be/QrSj4mKbRk0?si=7D5ZjXgW4eJqVYSp&t=8121

One of his central points is that Obsidian Sync isn't a good solution for collaboration because it forces you to share your whole vault, which means you're probably gonna need a specialized separate vault for your collaboration project, which breaks the whole network effect value prop of a connected vault. That's a central premise for me too. Thanks Yonatan, I'm gonna let him know about Relay

**Comment by mgmobrien** [comment]
Yonatan, this was a great tip. I'm putting you on our [wall of gratitude](https://system3.md/S3/Wall+of+Gratitude). Got a place for me to link to? maybe just https://github.com/yonatankremer

**Comment by yonatankremer** [comment]
haha thx, I have nowhere more interesting to link to. Hell I'm not even likely to use the product xD
